import { css } from 'glamor';
import { SectionCommonRoules } from '../GenerallCSS.js';

// ======================== Section Middle 3 =========================
export const SectionMiddle3CSS = {
    section3: css({
        'width': '100%',
        'height': '510px',
        'display': 'flex',
        'flexDirection': 'row',
    }),
    section3_1: css({
        'display': 'flex',
        'flexDirection': 'column',   
        'position': 'relative',
        'bottom': '0',
        'width': '45.5%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_1Row1: css({
        'position': 'relative',
        'top': '40px',
        'left': '3%',
        'width': '85%',
        'height': '120px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_4xSpdtContainer: css({
        'marginTop': '-30px',
        'width': '28%',
        'marginLeft': '20px',
        'display': 'flex',
        'flexDirection': 'row',
    }),
    section3_1Row1_1xSpdt: css({
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_2To4Spdt: css({
        'marginLeft': '100px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_2xRotarySpdt1xSpdt: css({
        'marginLeft': '50px',
        'width': '500px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_2xPushBtns: css({
        'position': 'relative',
        'top': '-50px',
        'left': '25px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
        'height': '170px',
    }),
    section3_1Row2: css({
        'marginTop': '-60px',
        'width': '1175px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'flex-end',
    }),
    // ===========================
    section3_1Row3: css({
        'position': 'relative',
        'top': '5px',
        'left': '130px',
        'width': '1100px',
        'display': 'flex',
        'flexDirection': 'row',
    }),
    section3_1Row3_2RotarySpdt1xPushBtn: css({
        'width': '40%',
        'marginTop': '20px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_PushBtn2: css({
        'marginTop': '-70px',
        'marginLeft': '-60px',
    }),
    section3_1Row3_Spdt4: css({
        'marginTop': '50px',
        'marginLeft': '70px',
    }),
    section3_1Row3PushBtn5To6:css({
        'position': 'relative',
        'width': '175px',
        'top': '10px',
        'left': '-10px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_PushBtn7: css({
        'position': 'relative',
        'top': '-60px',
        'left': '110px',
    }),
    section3_1Row3PushBtn8To9:css({
        'position': 'relative',
        'top': '10px',
        'left': '230px',
        'width': '175px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_2xRotarySpdt1xPushBtn: css({
        'width': '50%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================
    section3_1Row4: css({
        'width': '750px',
        'marginTop': '0',
        'marginLeft': '650px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row4Push1To2: css({
        'position': 'relative',
        'top': '-60px',
        'width': '175px',
        'left': '50px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_Rotary3: css({
        'position': 'relative',
        'top': '-60px',
        'left': '85px',
    }),
    section3_1Row4Push4To6: css({
        'position': 'relative',
        'top': '-60px',
        'width': '280px',
        'left': '55px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================
    section3_1Row5: css({
        'position': 'relative',
        'top': '-50px',
        'left': '3%',
        'width': '1297px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row5_Spdt1To3: css({
        'marginTop': '-4%',
        'marginLeft': '100px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row5_PushBtns4To10: css({
        'marginLeft': '278px',
        'width': '1231px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================================================
    section3_2: css({
        'width': '50%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_2Row1: css({
        'width': '100%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
        'marginTop': '20px',
    }),
    section3_2Row1_PushBtn2To3_5To6: css({
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
        'width': '50%',
    }),
    section3_2Row1_HorizontalSpdt4: css({
        'position': 'relative',
        'top': '-29px',
        'left': '25px',
    }),
    // ===========================
    section3_2Row2: css({
        'width': '97%',
        'marginLeft': '10px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
        'alignItems': 'Center',
        'marginBottom': '-33px',
    }),
    section3_2Row2_VericalSpdt1_6: css({
        'position': 'relative',
        'top': '-49px',
        'left': '25px',
    }),
    section3_2Row2_VericalSpdt2_5: css({
        'position': 'relative',
        'top': '-29px',
        'left': '25px',
    }),
    section3_2Row2_PushBtn2To4_9To10Container: css({
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_2Row2_PushBtn2To4_9To10: css({
        'width': '130px',
        'height': '70px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_2Row2_PushBtn7To8: css({
        'marginTop': '-98px',
        'height': '122px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_2Row3: css({
        'width': '95%',
        'marginLeft': '10px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
        'alignItems': 'Center',
        //'width': '90%',
    }),
    section3_2Row3_RotarySpdt1To2_7To8Container: css({
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_2Row3_RotarySpdt1To2_7To8: css({
        'marginTop': '20px',
        'width': '240px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_2Row3_RotarySpdt1_8: css({
        'marginTop': '-40px',
    }),
    section3_2Row3_PushBtn3To4_9Container: css({
        'position': 'relative',
        'top': '-45px',
        'left': '-47px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'center',
        'alignItems': 'center',
    }),
    section3_2Row3_PushBtn3To4_9: css({
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_2Row3_RotarySpdt6_11: css({
        'marginTop': '-40px',
    }),
    section3_2Row3_RotarySpdt5To6_10To11: css({
        'marginTop': '20px',
        'width': '240px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
        'alignItems': 'center',
    }),
    section3_2Row3_RotarySpdt12: css({
        'marginTop': '-66px',
    }),
    // ===========================================================
    section3_3: css({
        'width': '14%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_3Row1: css({
        'marginTop': '20px',
        'paddingLeft': '27px',
        'width': '100%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_3Row1VerticalSpdt2: css({
        'marginTop': '-40px',
    }),
    section3_3Row2: css({
        'width': '220px',
        'marginLeft': 'calc(50% - 110px)',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_3Row3: css({
        'width': '220px',
        'marginLeft': 'calc(50% - 110px)',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    // ===========================================================
    section3_4: css({
        'display': 'flex',
        'flexDirection': 'column',
        'width': '13%',
        'paddingLeft': '20px',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_4Row1: css({
        'marginTop': '60px',
        'marginLeft': '20px',
        'width': '82%',
        'height': '113px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row1Led2To3_LedSegment4: css({
        'height': '60px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'center',
        'alignItems': 'center',
    }),
    section3_4Row1Led2To3Container: css({
        'marginTop': '-30px',
        'width': '120px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'center',
    }),
    section3_4Row1LedSegment4: css({
        'marginTop': '35px',
    }),
    section3_4Row2: css({
        'marginTop': '20px',
        'marginLeft': '20px',
        'width': '87%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row2VerticalSpdt2To4: css({
        'marginTop': '35px',
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_4Row3: css({
        'marginTop': '43px',
        'marginLeft': '20px',
        'width': '87%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row3VerticalSpdt2To3: css({
        'marginTop': '35px',
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================================================
    section3_5: css({
        'width': '13%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_5Row1: css({
        'marginTop': '25px',
        'marginLeft': '40px',
        'height': '113px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row1Led1To3HorenzontalSpdt4: css({
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_4Row1HorenzontalSpdt4: css({
        'marginTop': '20px',
    }),
    section3_5Row2: css({
        'marginTop': '20px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_5Row3: css({
        'marginTop': '30px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }), 
    section3_5Row4: css({
        'marginTop': '43px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_5Row4RotaryEncorder1To2: css({
        'marginLeft': '40px',
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_5Row4VerticalSpdt3: css({
        'marginLeft': '80px',
    }),
}
