import { css } from 'glamor';
import { SectionCommonRoules } from '../GenerallCSS.js';

// ======================== Section Middle 3 =========================
export const SectionMiddle3CSS = {
    section3: css({
        'width': '100%',
        'height': '450px',
        'display': 'flex',
        'flexDirection': 'row',
    }),
    section3_1: css({
        'display': 'flex',
        'flexDirection': 'column',   
        'position': 'relative',
        'bottom': '0',
        'width': '40%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_1Row1: css({
        'position': 'relative',
        'top': '15px',
        'left': '3%',
        'width': '85%',
        'height': '120px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_4xSpdtContainer: css({
        'width': '28%',
        'marginLeft': '20px',
        'display': 'flex',
        'flexDirection': 'row',
    }),
    section3_1Row1_1xSpdt: css({
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_2To4Spdt: css({
        'marginLeft': '40px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_2xRotarySpdt1xSpdt: css({
        'width': '40%',
        'marginLeft': '100px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row1_2xPushBtns: css({
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_1Row2: css({
        'marginTop': '-55px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'flex-end',
    }),
    // ===========================
    section3_1Row3: css({
        'position': 'relative',
        'top': '-40px',
        'left': '50px',
        'width': '82.5%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_2RotarySpdt1xPushBtn: css({
        'width': '40%',
        'marginTop': '20px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_PushBtn2: css({
        'marginTop': '2px',
        'marginLeft': '-60px',
    }),
    section3_1Row3_Spdt4: css({
        'marginTop': '10px',
        'marginLeft': '10px',
    }),
    section3_1Row3_PushBtn7: css({
        'marginTop': '-20px',
    }),
    section3_1Row3_2xRotarySpdt1xPushBtn: css({
        'width': '50%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================
    section3_1Row4: css({
        'width': '49.59%',
        'marginTop': '-8%',
        'marginLeft': '48%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row3_Rotary3: css({
        'marginTop': '-20px',
        'marginLeft': '10%',
    }),
    // ===========================
    section3_1Row5: css({
        'position': 'relative',
        'top': '0',
        'left': '3%',
        'width': '94.5%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row5_Spdt1To3: css({
        'marginTop': '-4%',
        'marginLeft': '6%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_1Row5_PushBtns4To10: css({
        'marginLeft': '10%',
        'width': '90%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================================================
    section3_2: css({
        'width': '31%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_2Row1: css({
        'width': '100%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
        'marginTop': '20px',
    }),
    section3_2Row1_PushBtn2To3_5To6: css({
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
        'width': '50%',
    }),
    section3_2Row1_HorizontalSpdt4: css({
        'position': 'relative',
        'top': '-29px',
        'left': '25px',
    }),
    // ===========================
    section3_2Row2: css({
        'width': '97%',
        'marginLeft': '10px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
        'alignItems': 'Center',
        'marginBottom': '-33px',
    }),
    section3_2Row2_VericalSpdt1_6: css({
        'position': 'relative',
        'top': '-49px',
        'left': '25px',
    }),
    section3_2Row2_VericalSpdt2_5: css({
        'position': 'relative',
        'top': '-29px',
        'left': '25px',
    }),
    section3_2Row2_PushBtn2To4_9To10Container: css({
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_2Row2_PushBtn2To4_9To10: css({
        'width': '130px',
        'height': '70px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_2Row2_PushBtn7To8: css({
        'marginTop': '-98px',
        'height': '122px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_2Row3: css({
        'width': '95 %',
        'marginLeft': '10px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
        'alignItems': 'Center',
        //'width': '90%',
    }),
    section3_2Row3_RotarySpdt1To2_7To8Container: css({
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-between',
    }),
    section3_2Row3_RotarySpdt1To2_7To8: css({
        'marginTop': '20px',
        'width': '240px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_2Row3_RotarySpdt1_8: css({
        'marginTop': '-40px',
    }),
    section3_2Row3_PushBtn3To4_9Container: css({
        'position': 'relative',
        'top': '-45px',
        'left': '-47px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'center',
        'alignItems': 'center',
    }),
    section3_2Row3_PushBtn3To4_9: css({
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_2Row3_RotarySpdt6_11: css({
        'marginTop': '-40px',
    }),
    section3_2Row3_RotarySpdt5To6_10To11: css({
        'marginTop': '20px',
        'width': '240px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
        'alignItems': 'center',
    }),
    section3_2Row3_RotarySpdt12: css({
        'marginTop': '-66px',
    }),
    // ===========================================================
    section3_3: css({
        'width': '16%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_3Row1: css({
        'marginTop': '20px',
        'paddingLeft': '27px',
        'width': '100%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_3Row1VerticalSpdt2: css({
        'marginTop': '-40px',
    }),
    section3_3Row2: css({
        'width': '220px',
        'marginLeft': 'calc(50% - 110px)',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_3Row3: css({
        'width': '220px',
        'marginLeft': 'calc(50% - 110px)',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    // ===========================================================
    section3_4: css({
        'display': 'flex',
        'flexDirection': 'column',
        'width': '13%',
        'paddingLeft': '20px',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_4Row1: css({
        'marginTop': '20px',
        'marginLeft': '20px',
        'width': '82%',
        'height': '113px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row1Led2To3_LedSegment4: css({
        'height': '60px',
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'center',
        'alignItems': 'center',
    }),
    section3_4Row1Led2To3Container: css({
        'marginTop': '-30px',
        'width': '120px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'center',
    }),
    section3_4Row1LedSegment4: css({
        'marginTop': '13px',
    }),
    section3_4Row2: css({
        'marginTop': '20px',
        'marginLeft': '20px',
        'width': '87%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row2VerticalSpdt2To4: css({
        'marginTop': '35px',
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    section3_4Row3: css({
        'marginTop': '43px',
        'marginLeft': '20px',
        'width': '87%',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-around',
    }),
    section3_4Row3VerticalSpdt2To3: css({
        'marginTop': '35px',
        'width': '130px',
        'display': 'flex',
        'flexDirection': 'row',
        'justifyContent': 'space-between',
    }),
    // ===========================================================
    section3_5: css({
        'width': '10%',
        'backgroundColor': SectionCommonRoules.colorGrey,
        'borderRight': SectionCommonRoules.border3B,
    }),
    section3_6: css({
        'bottom': '0',
        'width': '10%',
        'backgroundColor': SectionCommonRoules.colorGrey,
    }),
    section3_6InnerFrame: css({
        'display': 'flex',
        'flexDirection': 'rox',
        'width': '300px',
        'marginLeft': '15px',
    }),
    section3_6LedSpdt: css({
        'display': 'flex',
        'flexDirection': 'column',
        'justifyContent': 'space-betwween',
        'width': '50px',
    }),
}
